export const submittedFields = [
    { key: 'height', label: 'Altura (cm)' },
    { key: 'current_weight', label: 'Peso actual (kg)' },
    { key: 'waist_circumference', label: 'Cintura (cm)' },
    { key: 'hip_circumference', label: 'Cadera (cm)' },
    { key: 'goal_type', label: 'Objetivo' },
    { key: 'medical_condition', label: 'Condición médica' },
    { key: 'allergies', label: 'Alergias' },
    { key: 'medications', label: 'Medicamentos' },
    { key: 'preexisting_condition', label: 'Condición preexistente' },
    { key: 'digestive_issues', label: 'Problemas digestivos' },
    { key: 'past_surgeries', label: 'Cirugías pasadas' },
    { key: 'fitness_level', label: 'Nivel de actividad física' },
    { key: 'work_activity', label: 'Tipo de trabajo' },
    { key: 'exercise_frequency', label: 'Frecuencia de ejercicio' },
    { key: 'exercise_type', label: 'Tipo de ejercicio' },
    { key: 'meals_per_day', label: 'Comidas al día' },
    { key: 'meal_schedule', label: 'Horario de comidas' },
    { key: 'dietary_preferences', label: 'Preferencias dietéticas' },
    { key: 'favorite_foods', label: 'Comidas favoritas' },
    { key: 'avoided_foods', label: 'Comidas evitadas' },
    { key: 'water_intake', label: 'Consumo de agua (vasos/día)' },
    { key: 'alcohol_caffeine_consumption', label: 'Alcohol / Cafeína' },
    { key: 'budget', label: 'Presupuesto' },
    { key: 'cooking_time', label: 'Tiempo para cocinar' },
];
